[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
;ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/rule/Custom_Direct.list
ruleset=🛑 广告拦截,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/adobe.list
ruleset=🍃 应用净化,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/IDM.list
ruleset=🍃 应用净化,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/BanProgramAD.list
ruleset=🤖 OpenAi,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/AI.list
;ruleset=🤖 OpenAi,https://gh-proxy.com/https://github.com/juewuy/ShellCrash/blob/master/rules/ai.list
;ruleset=🤖 OpenAi,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/Copilot.list
;ruleset=🤖 OpenAi,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/GithubCopilot.list
;ruleset=🤖 OpenAi,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/Claude.list
ruleset=☁️ CloudFlareWebsite,https://gh-proxy.com/https://github.com/0xwzluo/ACL4SSR/blob/main/Cloudflare-Website.list
ruleset=☁️ CloudFlareCDN,[]GEOIP,cloudflare
ruleset=☁️ CloudFlareCDN,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/CloudflareCIDR.list
ruleset=🐳 Docker镜像,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Docker.list
ruleset=💻 GitHub,https://gh-proxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/GitHub/GitHub.list
ruleset=📹 油管视频,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/YouTube.list
ruleset=📢 谷歌FCM,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌FCM,https://gh-proxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Google/Google.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/GoogleCN.list
;BT Tracker 相关域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/SteamCN.list
ruleset=🛜 SpeedTest,https://gh-proxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Speedtest/Speedtest.list
ruleset=Ⓜ️ 微软Bing,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Apple.list
ruleset=📲 电报消息,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Telegram.list
ruleset=🎶 网易音乐,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Nintendo.list
;各大游戏平台下载域名直连
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/Aethersailor/Custom_OpenClash_Rules/blob/main/rule/Steam_CDN.list
ruleset=🎵 TikTok,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/TikTok.list
ruleset=🎥 奈飞视频,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Netflix.list
ruleset=📺 巴哈姆特,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/Emby.list
ruleset=🚀 节点选择,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://gh-proxy.com/https://github.com/UlinoyaPed/ShellClash/blob/dev/lists/proxy.list
ruleset=🚀 节点选择,https://gh-proxy.com/https://github.com/cmliu/ACL4SSR/blob/main/Clash/CMBlog.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/UlinoyaPed/ShellClash/blob/dev/lists/direct.list
;ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🎯 全球直连`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]⚡ 其它节点
custom_proxy_group=♻️ 自动选择`url-test`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=☑️ 手动切换`select`^(.*)$
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=☁️ CloudFlareWebsite`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🐟 漏网之鱼
custom_proxy_group=☁️ CloudFlareCDN`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🐟 漏网之鱼
custom_proxy_group=🤖 OpenAi`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🐳 Docker镜像`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=💻 GitHub`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🛜 SpeedTest`select`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|🇭🇰|Hong Kong|HongKong|hongkong|HKG)`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇺🇸 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|🇺🇸|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|🇯🇵|Japan|Tokyo|NRT|KIX)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|🇸🇬|Singapore|SIN)`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=📶 官方优选`url-test`^((官方|防|电信|联通|移动|CT|CU|CM|CF|t.me|WARP|Warp|warp).*)$`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇩🇪 德国节点`url-test`(DE|🇩🇪|德国)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇬🇧 英国节点`url-test`(GB|🇬🇧|英国)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇳🇱 荷兰节点`url-test`(NL|🇳🇱|荷蘭|荷兰)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|🇰🇷|Korea|KOR|Seoul|首尔|春川|韩|韓|ICN)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇫🇷 法国节点`url-test`(FR|🇫🇷|法国)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🇵🇱 波兰节点`url-test`(PL|🇵🇱|波|华沙)`[]REJECT`https://www.gstatic.com/generate_204`300,,200
custom_proxy_group=⚡ 其它节点`select`^((?!.*电信)(?!.*联通)(?!.*移动)(?!.*美)(?!.*US)(?!.*us)(?!.*🇺🇸)(?!.*港)(?!.*HK)(?!.*hk)(?!.*🇭🇰)(?!.*日本)(?!.*JP)(?!.*jp)(?!.*🇯🇵)(?!.*新加坡)(?!.*狮城)(?!.*SG)(?!.*sg)(?!.*🇸🇬)(?!.*德国)(?!.*DE)(?!.*de)(?!.*🇩🇪)(?!.*英国)(?!.*GB)(?!.*gb)(?!.*🇬🇧)(?!.*荷兰)(?!.*NL)(?!.*nl)(?!.*🇳🇱)(?!.*韩国)(?!.*KR)(?!.*kr)(?!.*🇰🇷)(?!.*法国)(?!.*FR)(?!.*fr)(?!.*🇫🇷)(?!.*波)(?!.*华沙)(?!.*PL)(?!.*pl)(?!.*🇵🇱).*)$`300,,200
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`(NF|奈飞|解锁|Netflix|NETFLIX|Media|MITM)`[]🎯 全球直连
custom_proxy_group=📺 巴哈姆特`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`[]🎯 全球直连
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点`(MITM|emby|Emby)`[]🎯 全球直连
custom_proxy_group=🌏 国内媒体`select`[]🎯 全球直连`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点
custom_proxy_group=Ⓜ️ 微软Bing`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇬🇧 英国节点`[]🇳🇱 荷兰节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇵🇱 波兰节点`[]🇰🇷 韩国节点
custom_proxy_group=🎶 网易音乐`select`[]🎯 全球直连`[]🚀 节点选择`[]📶 官方优选`[]🇭🇰 香港节点`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]☑️ 手动切换`[]📶 官方优选`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]🎯 全球直连
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]🎯 全球直连
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
rename_node=!!script:function rename(node){return node.Remark+="--hhhhh";}
;rename_node=!!script%3Afunction%20r()%7Bvar%20m%3D%7B%7D%3Breturn%20function%20rename(n)%7Breturn%20m%5Bn.Remark%5D%3F(%2B%2Bm%5Bn.Remark%5D%2Cn.Remark%2B'-'%2Bm%5Bn.Remark%5D)%3A(m%5Bn.Remark%5D%3D1%2Cn.Remark)%7D%7D()
rename=!!script:function rename(node){return node.Remark+="--hhhhh";}
;rename=!!script%3Afunction%20r()%7Bvar%20m%3D%7B%7D%3Breturn%20function%20rename(n)%7Breturn%20m%5Bn.Remark%5D%3F(%2B%2Bm%5Bn.Remark%5D%2Cn.Remark%2B'-'%2Bm%5Bn.Remark%5D)%3A(m%5Bn.Remark%5D%3D1%2Cn.Remark)%7D%7D()

clash_rule_base=https://gh-proxy.com/https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/GeneralClashConfig.yml

;luck
